[character] # https://starship.rs/config/#character
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[docker_context] # https://starship.rs/config/#docker-context
disabled = true

[gcloud] # https://starship.rs/config/#google-cloud-gcloud
disabled = true
